---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    image_name: zuul-ci.org/zuul-operator:testing
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/zuul-ci_v1alpha1_zuul_cr.yaml'])) | from_yaml }}"
  tasks:
  - name: Create the zuul-ci.org/v1alpha1.Zuul
    k8s:
      namespace: '{{ namespace }}'
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/zuul-ci_v1alpha1_zuul_cr.yaml'])) }}"

  - name: Get the newly created Custom Resource
    debug:
      msg: "{{ lookup('k8s', group='zuul-ci.org', api_version='v1alpha1', kind='Zuul', namespace=namespace, resource_name=custom_resource.metadata.name) }}"

  - name: Wait 40s for reconciliation to run
    k8s_facts:
      api_version: 'v1alpha1'
      kind: 'Zuul'
      namespace: '{{ namespace }}'
      name: '{{ custom_resource.metadata.name }}'
    register: reconcile_cr
    until:
    - "'Successful' in (reconcile_cr | json_query('resources[].status.conditions[].reason'))"
    delay: 4
    retries: 10

- import_playbook: "{{ playbook_dir }}/../default/asserts.yml"
